layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: true
    forks: true
    projects:
    repo-name: somaditya, somaditya.github.io

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  hackerrank: somaditya
  # instagram: somaditya.eth
  # keybase: your_username
  linkedin: somadityabasak
  # mastodon: your_username
  # medium: somaditya
  stackoverflow: 8017984
  # telegram: somaditya_eth
  twitter: sbk1337
  # unsplash: your_username
  # vk: your_username
  website: https://linktr.ee/somaditya
  # youtube: your_username

topics:
  - name: Java
    web_url: https://www.oracle.com/java/
    image_url: https://cdn-icons-png.flaticon.com/512/226/226777.png
  
  - name: Data Structures
    web_url: https://github.com/topics/data-structures
    image_url: https://hackr.io/tutorials/data-structures-algorithms/logo-data-structures-algorithms.svg?ver=1587721467
  
  - name: Algorithms
    web_url: https://github.com/topics/algorithms
    image_url: https://cdn-icons-png.flaticon.com/512/1822/1822206.png
