layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  hackerrank: somaditya
  # instagram: binary.hash
  # keybase: your_username
  linkedin: somadityabasak
  # mastodon: your_username
  medium: somaditya
  # stackoverflow: 8017984
  telegram: somaditya_eth
  twitter: somaditya_eth
  # unsplash: your_username
  # vk: your_username
  website: https://github.com/somaditya
  # youtube: your_username

topics:
  - name: Camunda
    web_url: https://github.com/camunda
    image_url: https://avatars.githubusercontent.com/u/2443838?s=200&v=4

  - name: JavaScript
    web_url: https://github.com/topics/javascript
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/javascript/javascript.png

  - name: Node.js
    web_url: https://github.com/topics/nodejs
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/nodejs/nodejs.png
