layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  exclude:
    archived: false
    forks: false
    projects: somaditya.github.io
    repo-name: somaditya.github.io

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  hackerrank: somaditya
  leetcode: somaditya
  # instagram: somaditya.eth
  # keybase: your_username
  linkedin: somadityabasak
  # mastodon: your_username
  # medium: somaditya
  # stackoverflow: 8017984
  # telegram: somaditya_eth
  twitter: 5n0w_cr45h
  # unsplash: your_username
  # vk: your_username
  website: https://linktr.ee/somaditya
  # youtube: your_username

topics:
  - name: Agentic AI
    web_url: https://en.wikipedia.org/wiki/AI_agent
    image_url: https://cdn-icons-png.flaticon.com/512/6134/6134346.png

  - name: Data Structures
    web_url: https://github.com/topics/data-structures
    image_url: https://cdn-icons-png.flaticon.com/512/1042/1042009.png

  - name: Algorithms
    web_url: https://github.com/topics/algorithms
    image_url: https://cdn-icons-png.flaticon.com/512/1822/1822206.png
